adding index.html and style.css file
Takhmina175/theNextWeb_ClonePage pull request #1
Opened 2020-09-24 15:24 UTC by okusarobert

This PR consists of replicating the The Next Web website putting emphasis on how it behaves differently depending on the size of the screen where the website is rendered.

2020-10-01 00:30 UTC, blackpintz requested changes
# Status: Changes Required

## Hello team,

**Great job on your project. However, there are some required changes before the project can be approved.**

## Mandatory

### Large screen (min-width: 1024 px)
**Note: min-width is 1024px for large screens and not 1440px as used.**

1).  **The navigation bar and the top section of your page does not look like the original and here is why:**
  

original | clone
---------| -------
![navtnw_original](https://user-images.githubusercontent.com/38922385/94747050-bc06df00-0386-11eb-8531-860aca775a2c.png) | ![navtnw_clone](https://user-images.githubusercontent.com/38922385/94747074-c88b3780-0386-11eb-87ac-695e42582aa2.png)

- **The TNW logo should not be displayed on the top leftmost part but should be a small logo on the rightmost part next to the clock and search icon.**

- **Topmost menu,(with a black background), should be displayed on the leftmost part of the page.**

- **The small text in the yellow background overlaps bottom section with background images.**

- **For the sections that have a background image, some of the text and icons are hidden. Also, reduce the text font-size.**

2). **The topmost menu, (with a back background ), should not have a sticky position.**

3). **Latest News section**

original | clone
---------| -------
![latest_original](https://user-images.githubusercontent.com/38922385/94748511-28371200-038a-11eb-8076-42152e21abbe.png) | ![latest_clone](https://user-images.githubusercontent.com/38922385/94748530-3422d400-038a-11eb-819d-338874489f57.png)

- **Each row should display four images instead of three.**

- **There is some text displaying behind the images. (Check the first and second images below the title).**

- **There is some text next to the Latest news title that should not be there.**

- **Reduce the headline font-size.**

4). **Latest Funding round Section**

original | clone
---------| -------
![funding_original](https://user-images.githubusercontent.com/38922385/94749355-4c93ee00-038c-11eb-9280-923f61de5cdc.png) | ![funding_clone](https://user-images.githubusercontent.com/38922385/94749293-2bcb9880-038c-11eb-8343-2846e806b961.png)

- **All the titles are displayed on one line.**

- **The row is divided into four sections of content and not three.**

5). **The sections after.**

original | clone
---------| -------
![hardfork_original](https://user-images.githubusercontent.com/38922385/94749930-a47f2480-038d-11eb-8663-ea3fac2467f7.png) | ![hardfork_clone](https://user-images.githubusercontent.com/38922385/94749959-b365d700-038d-11eb-9686-82fa111c60a5.png)

- **Each row displays three images instead of two.**

- **The rows content overlap each other.**

- **Add a list-style-type to the lists.**

- **Reduce the content font-size so it doesn't look as big as the image.**

6). **For the latest deals section, the row displays four images and not three.**

### Medium screen ( min-width: 768px)

1). **The TNW logo should not display on the medium screen.**

original | clone
---------| -------
![tnwmedium_original](https://user-images.githubusercontent.com/38922385/94752648-823cd500-0394-11eb-8ba2-3ff1626effc2.png) | ![tnwmedium_clone](https://user-images.githubusercontent.com/38922385/94752669-8ec12d80-0394-11eb-867b-376e6d207487.png)



### Small screen

1).  **Navigation bar and the top section of your page.**

original | clone
---------| -------
![smalltnw_original](https://user-images.githubusercontent.com/38922385/94751248-b8785580-0390-11eb-94e1-41ff70e202f6.png) | ![smalltnw_clone](https://user-images.githubusercontent.com/38922385/94751270-c9c16200-0390-11eb-9683-96262bb312d2.png)

- **Please fix the icon display so it looks like the original.**

- **I can see page content, above the yellow background, as I scroll down the page.**

- **The sections with image backgrounds either don't have text content or some parts of the contents are hidden.**

2). **For the other sections of the page, reduce the text font-size especially for the content with background images.**

3). **Increase the background image height for the other sections as well. See the example below.**

original | clone
---------| -------
![hfsmall_original](https://user-images.githubusercontent.com/38922385/94752152-11e18400-0393-11eb-9baf-f9bfa6b2fb47.png) | ![hfsmall_clone](https://user-images.githubusercontent.com/38922385/94752171-1c038280-0393-11eb-8607-de8f8d7d8076.png)

- **Also fix the font-size for the lists. (Check the screenshot above).**

#### Happy coding 😃.
**PS: You can reach me on slack(Rose Wanjohi).**

2020-10-01 10:53 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-10-01 11:09 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Takhmina175 and @okusarobert
Good job with the changes! :tada: We are almost there.
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Fix spacing issues as @blackpintz explained in her review
- [ ] Remove `!important `from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)

### Header
- [ ] Manage the header text in your clone

|[Source Page](https://thenextweb.com/)|[Clone Page](https://takhmina175.github.io/theNextWeb_ClonePage/)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/94801177-193e7700-03ff-11eb-808c-1797c380b0e6.png)|![clone](https://user-images.githubusercontent.com/29689273/94801189-1cd1fe00-03ff-11eb-9c53-e483bc5a8bfe.png)|

### Latest Funding
- [ ] manage the links on 813px

|[Source Page](https://thenextweb.com/)|[Clone Page](https://takhmina175.github.io/theNextWeb_ClonePage/)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/94801564-a97cbc00-03ff-11eb-8b15-f7165fa39a4f.png)|![clone](https://user-images.githubusercontent.com/29689273/94801570-aaade900-03ff-11eb-9967-af47fc2065e1.png)|


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-01 11:09 UTC, umairarshadbutt commented on style.css
> +    position: static !important;
Remove `!important`

2020-10-01 11:09 UTC, umairarshadbutt commented on style.css
> +    z-index: auto !important;
Remove `!important`

2020-10-01 11:09 UTC, umairarshadbutt commented on style.css
> +    display: none !important;
Remove `!important`

2020-10-01 11:09 UTC, umairarshadbutt commented on style.css
> +    position: static !important;
Remove `!important`

2020-10-01 11:09 UTC, umairarshadbutt commented on style.css
> +    z-index: auto !important;
Remove `!important`

2020-10-01 11:09 UTC, umairarshadbutt commented on style.css
> +    z-index: auto !important;
Remove `!important`

2020-10-01 17:40 UTC, teekaytech requested changes
## Status: Changes Required :warning: :construction:

### Hi team :wave: 
Good job with the changes! :ok_hand: We are almost there.
However, we do have some changes to carry out before we proceed (see comments below).

**[ REQUIRED CHANGES ]** 

- [ ] The main navigation section and the sub navigation section should be rendered at large screen sizes.
- Right now, you're only rendering the sub-navigation section for large screen sizes (1024px and above).

Source page:
![18:17:20](https://user-images.githubusercontent.com/26856491/94841785-709a1280-0412-11eb-90e5-aaf34d68fd79.png)

Clone page:
![18:17:50](https://user-images.githubusercontent.com/26856491/94841808-74c63000-0412-11eb-890f-036f0e1543e1.png)

- [ ] Remove the `TNW` logo on top of the featured article for medium screen sizes (768px to 1023px)

Source page:
![18:22:35](https://user-images.githubusercontent.com/26856491/94842305-26656100-0413-11eb-8a04-b0df4d7aad7c.png)

Clone page:
![18:22:57](https://user-images.githubusercontent.com/26856491/94842352-32e9b980-0413-11eb-892c-4098021cbdcf.png)

- [ ] You have some issues to fix in the footer section.

![18:27:51](https://user-images.githubusercontent.com/26856491/94842892-d5a23800-0413-11eb-89c6-2911dcd5a01e.png)

- On large screen sizes, the footer occupies a single line. **Note that it does not change across breakpoints.** This implies that if the footer breaks, it should be driven by the content.

Source page:
![18:30:20](https://user-images.githubusercontent.com/26856491/94843172-3a5d9280-0414-11eb-8a0a-19de2db3e9df.png)

Clone page:
![18:30:37](https://user-images.githubusercontent.com/26856491/94843182-3df11980-0414-11eb-9123-30d6fae9a907.png)

- On medium small screen size, the social media icons seems to be overlapping.

| Source page      | Clone page |
| ----------- | ----------- |
| ![18:32:08](https://user-images.githubusercontent.com/26856491/94843360-801a5b00-0414-11eb-94a0-01967b2425ec.png)      | ![18:32:20](https://user-images.githubusercontent.com/26856491/94843373-84df0f00-0414-11eb-920c-4562f5da1079.png)       |


* **When you have made the specified changes, please submit another code review. Thank you!**
* **If you feel like you need help or you have any question(s), I'm @taofeekolalere on slack**

Regards,
[Taofeek Olalere](https://github.com/teekaytech)
Happy Coding :technologist:

2020-10-02 18:18 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

#### Hello @Takhmina175 and @okusarobert

Your progress is amazing, well done on implementing all the requested changes 👍 

There are still some changes that are necessary for this project to be approved.

- [ ] Looks like you lost the **TNW** on the larger screen after fixing it for the medium screen. See screenshot below

- [ ] [Optional] There is a gradient overlay that allows the text to be more pronounced.
![feature](https://user-images.githubusercontent.com/5264771/94954709-672bab80-04e1-11eb-92e6-1b950b2849c1.jpg)

- [ ] Your footer on the large screen still has some work to do, see the screenshot below. 
- The spacing is too much compared to the original
- The spacing between the social media icons is much
- Increase the size of the menu items below the social media icons
- Increase the social media icon size and reduce its padding
Just compare the clone and the original, it doesn't have to be perfect, close enough is good.
Perfect would be awesome though 😄 
![tnwfooter](https://user-images.githubusercontent.com/5264771/94955991-5714cb80-04e3-11eb-924b-f21fdaa1ba07.jpg)

Fix these changes and submit another code review request and you should be good to go.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-10-03 00:41 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Hello team!
What amazing work you have been doing in this project! 👍 
Just a few more steps to get it approved 💪 

Kindly, check my comments below 👇  apply the changes and request a new code review ⏩ 

Good luck! 😃 

## Changes
- You have an overlay for screens below 1024px, kindly fix it.
![Capture](https://user-images.githubusercontent.com/56809963/94979000-9ca3b980-0520-11eb-9063-4069be61f836.PNG)
- The main navbar at 1024px does not match the original, please modify it
original:
![Capture2](https://user-images.githubusercontent.com/56809963/94979065-fd32f680-0520-11eb-9478-e10b8d9727ed.PNG)
Your project:
![Capture1](https://user-images.githubusercontent.com/56809963/94979070-07ed8b80-0521-11eb-8399-92418ef51d58.PNG)
- For small screens, 768px and below, the text is missing in the main section
![Capture3](https://user-images.githubusercontent.com/56809963/94979108-3d927480-0521-11eb-9456-82b963ebff25.PNG)
- For small devices, the hard-fork section has a problem with the list, it should match the width of the photo and the rest of the item
Your project:
![Capture4](https://user-images.githubusercontent.com/56809963/94979152-7df1f280-0521-11eb-9ed1-0390c7afb784.PNG)
Original:
![Capture5](https://user-images.githubusercontent.com/56809963/94979170-96620d00-0521-11eb-9542-bb5b6662e9be.PNG)
- In this same section, the space between the list items must be bigger and the image size also must be bigger, kindly fix it.

2020-10-03 08:42 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__I must say, you've done well implementing the changes required by the previous reviewers. However, there are some changes that are required to be fixed before this project can be approved. Please check my points below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] As the previous reviewer mentioned, try to add some space after each section. You can also reduce the font size and boldness so it matches the source page. Right now, things look so clumsy in your page.

![09:19:33](https://user-images.githubusercontent.com/26856491/94986800-98e05900-0559-11eb-92fc-0d8f2373c23d.png)

Source page:
![09:21:39](https://user-images.githubusercontent.com/26856491/94986850-fd9bb380-0559-11eb-8c26-b25fd4143087.png)

Clone page:
![09:20:48](https://user-images.githubusercontent.com/26856491/94986859-0ab8a280-055a-11eb-8568-f11a4ec49fa2.png)

- [ ] As an improvement to what the immediate past reviewer mentioned, you should improve on the general layout of your `Insights`, `Podium`, `Creative`, `Tech` and similar sections of your page

- As an example, see the `Creative` section below and observe the difference, then use it to modify others.

Source page:
![09:35:16](https://user-images.githubusercontent.com/26856491/94987177-1e650880-055c-11eb-84f8-c3f41af55917.png) 

Clone page: 
![09:34:09](https://user-images.githubusercontent.com/26856491/94987182-291f9d80-055c-11eb-9f48-c3a66fa3b31e.png) |

**[ OPTIONAL CHANGES ]**

- [ ] Please pay attention to margins and paddings as seen in the source page.

**Please do not give up on these changes, the project is close to completion. Kindly make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-10-03 10:37 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Hello team!
Good job implementing some changes 👍 
But we still need some changes to do before approving this project 💪 
Kindly, check my  comments below 👇  and after they are done resubmit your project for a new code review

## Changes
- Latest findings section must have only 3 items in screens below 1024px, please remove the extra item for mobile screens
- In screens above 1024px all your sections have an extra horizontal margin, please make it look like the original.
- For small screens, 768px and below, the text is still missing in the main section
- As the previous TSE mentioned, please fix the image's width in the latest section in the Insights, Podium, Creative, Tech sections.
- In the Insights, Podium, Creative, Tech sections for screens above 1024px there is too much margin-bottom, while in smaller screens I can still see overlay(between 1024px and 810px), kindly fix it.

2020-10-04 22:48 UTC, kitpao requested changes
# 👋 Hello @Takhmina175 !!

You are almost done :) 🌟 great job implementing almost all required changes

Kidly check below the 3 remaining issues (extra space, horizontal scrollbar and overlap):

- **[REQUIRED]**  Please check the differences below:
**TABLET**
- [ ] Please see the annotations and fix them:
![image](https://user-images.githubusercontent.com/53256139/95028590-b7804600-0666-11eb-8167-973611e624b5.png)
- [ ] You still have overlayed content between sections, to fix it, just remove the fixed height and let it accommodate by itself:
```
@media (min-width: 768px)
constructed stylesheet
.container-height {
    height: 670px;                                 <------- delete this
}
```
![image](https://user-images.githubusercontent.com/53256139/95028804-991b4a00-0668-11eb-9eba-f552ec3ad948.png)

**_Note:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

- **OPTIONAL** Not required since it was not required by previous TSE, but for next time, pay attention to details like these:
![image](https://user-images.githubusercontent.com/53256139/95028371-6c196800-0665-11eb-93c8-87bf4da8e15f.png)
![image](https://user-images.githubusercontent.com/53256139/95028422-c1ee1000-0665-11eb-9651-9c98b8734854.png)

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate if can leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😛 

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-10-05 09:55 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Takhmina175 and @okusarobert
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Remove commented code from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)
- [ ] Fix the navbar issue as mentioned before
### Funding section
- Fix the text overlapping issue on medium and small screens

|[Source Page](https://thenextweb.com/)|[Clone Page](https://takhmina175.github.io/theNextWeb_ClonePage/)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/95064858-bfe58900-0719-11eb-877a-6378bbac0be7.png)|![clone](https://user-images.githubusercontent.com/29689273/95064970-dbe92a80-0719-11eb-9d4d-cd384e43753c.png)|

|[Source Page](https://thenextweb.com/)|[Clone Page](https://takhmina175.github.io/theNextWeb_ClonePage/)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/95065162-1d79d580-071a-11eb-94ec-8dc496fa4afa.png)|![clone](https://user-images.githubusercontent.com/29689273/95065167-1f439900-071a-11eb-99c8-d809b167a3d4.png)|

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-05 15:13 UTC, merged

2020-10-06 02:06 UTC, arslanbisharat reviewed
# Congratslutons  Approved :tada:
-------------------------------------------------------------------------------------------------
Hello Developer :wave:
You are on :fire:
Thank you so much for making those changes and I am very happy to approve the project. You have done a great job. :clap:
Please keep working hard and move forward with your curriculum. 
Looking forward to seeing your next project. :smile:

**To highlight** 

- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍

**Optional** Please make your PR more descriptive by adding more details about your project.This can help TSEs to review your project and your PR looks professional.  
--------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
@arslan Bisharat on slack in the case you want to discuss anything.**